import { createClient } from '@supabase/supabase-js'
import 'dotenv/config'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!
const supabase = createClient(supabaseUrl, supabaseKey)

const tables = [
  'cf_titulos', 'cf_capitulos', 'cf_secoes', 'cf_subsecoes',
  'cf_artigos', 'cf_paragrafos', 'cf_incisos', 'cf_alineas',
  'stf_decisoes', 'cf_vinculos', 'stf_sumulas', 'ec_emendas',
]

async function fix() {
  console.log('Alterando colunas id para GENERATED BY DEFAULT...\n')

  for (const table of tables) {
    const { error } = await supabase.rpc('exec_sql', {
      query: `ALTER TABLE ${table} ALTER COLUMN id SET GENERATED BY DEFAULT;`
    })
    if (error) {
      console.log(`  ✗ ${table}: ${error.message}`)
    } else {
      console.log(`  ✓ ${table}`)
    }
  }
}

fix()
