-- CREATE TYPE tipo_artigo AS ENUM ('CF', 'ADCT');
CREATE TYPE tipo_paragrafo AS ENUM ('unico', 'numerado');
CREATE TYPE orgao_julgador AS ENUM ('P', '1T', '2T', 'mono');
CREATE TYPE tipo_bloco AS ENUM ('concentrado', 'repercussao_geral', 'correlato', 'sumula');
CREATE TYPE status_jurisprudencial AS ENUM ('reafirmacao', 'oscilacao', 'reversao', 'fragmentacao', 'nao_classificado');
CREATE TYPE tipo_sumula AS ENUM ('vinculante', 'comum');

CREATE TABLE cf_titulos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_romano TEXT    NOT NULL,
    numero_int    INTEGER NOT NULL UNIQUE,
    denominacao   TEXT    NOT NULL,
    cor_hex       CHAR(7) NOT NULL,
    ordem         INTEGER NOT NULL UNIQUE
);

CREATE TABLE cf_capitulos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_id     BIGINT  NOT NULL REFERENCES cf_titulos(id) ON DELETE CASCADE,
    numero_romano TEXT    NOT NULL,
    numero_int    INTEGER NOT NULL,
    denominacao   TEXT    NOT NULL,
    ordem         INTEGER NOT NULL,
    UNIQUE (titulo_id, numero_int)
);

CREATE TABLE cf_secoes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capitulo_id   BIGINT  REFERENCES cf_capitulos(id) ON DELETE CASCADE,
    titulo_id     BIGINT  NOT NULL REFERENCES cf_titulos(id) ON DELETE CASCADE,
    numero_romano TEXT    NOT NULL,
    numero_int    INTEGER NOT NULL,
    denominacao   TEXT    NOT NULL,
    ordem         INTEGER NOT NULL
);

CREATE TABLE cf_subsecoes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secao_id      BIGINT  NOT NULL REFERENCES cf_secoes(id) ON DELETE CASCADE,
    numero_romano TEXT    NOT NULL,
    numero_int    INTEGER NOT NULL,
    denominacao   TEXT    NOT NULL,
    ordem         INTEGER NOT NULL
);

CREATE TABLE cf_artigos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero        INTEGER NOT NULL,
    numero_texto  TEXT    NOT NULL,
    caput         TEXT    NOT NULL,
    tipo          tipo_artigo NOT NULL DEFAULT 'CF',
    titulo_id     BIGINT  REFERENCES cf_titulos(id) ON DELETE SET NULL,
    capitulo_id   BIGINT  REFERENCES cf_capitulos(id) ON DELETE SET NULL,
    secao_id      BIGINT  REFERENCES cf_secoes(id) ON DELETE SET NULL,
    subsecao_id   BIGINT  REFERENCES cf_subsecoes(id) ON DELETE SET NULL,
    ordem         INTEGER NOT NULL,
    vigente       BOOLEAN NOT NULL DEFAULT TRUE,
    alterado_por_ec INTEGER[],
    UNIQUE (numero, tipo)
);

CREATE TABLE cf_paragrafos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artigo_id     BIGINT  NOT NULL REFERENCES cf_artigos(id) ON DELETE CASCADE,
    tipo          tipo_paragrafo NOT NULL,
    numero        INTEGER,
    numero_texto  TEXT    NOT NULL,
    texto         TEXT    NOT NULL,
    ordem         INTEGER NOT NULL
);

CREATE TABLE cf_incisos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artigo_id       BIGINT  NOT NULL REFERENCES cf_artigos(id) ON DELETE CASCADE,
    paragrafo_id    BIGINT  REFERENCES cf_paragrafos(id) ON DELETE CASCADE,
    numero_romano   TEXT    NOT NULL,
    numero_int      INTEGER NOT NULL,
    texto           TEXT    NOT NULL,
    ordem           INTEGER NOT NULL
);

CREATE TABLE cf_alineas (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inciso_id BIGINT NOT NULL REFERENCES cf_incisos(id) ON DELETE CASCADE,
    letra     CHAR(1) NOT NULL,
    texto     TEXT    NOT NULL,
    ordem     INTEGER NOT NULL,
    UNIQUE (inciso_id, letra)
);

CREATE TABLE stf_decisoes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe          TEXT    NOT NULL,
    numero          TEXT    NOT NULL,
    classe_numero   TEXT    NOT NULL UNIQUE,
    relator         TEXT,
    data_julgamento DATE,
    data_dje        DATE,
    orgao_julgador  orgao_julgador,
    ementa          TEXT,
    integra_url     TEXT,
    downloaded      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE cf_vinculos (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artigo_id              BIGINT  NOT NULL REFERENCES cf_artigos(id) ON DELETE CASCADE,
    paragrafo_id           BIGINT  REFERENCES cf_paragrafos(id) ON DELETE SET NULL,
    inciso_id              BIGINT  REFERENCES cf_incisos(id) ON DELETE SET NULL,
    alinea_id              BIGINT  REFERENCES cf_alineas(id) ON DELETE SET NULL,
    decisao_id             BIGINT  NOT NULL REFERENCES stf_decisoes(id) ON DELETE CASCADE,
    tipo_bloco             tipo_bloco NOT NULL,
    status_jurisprudencial status_jurisprudencial NOT NULL DEFAULT 'nao_classificado',
    texto_contexto         TEXT,
    ordem                  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE stf_sumulas (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero    INTEGER NOT NULL,
    tipo      tipo_sumula NOT NULL,
    enunciado TEXT    NOT NULL,
    vigente   BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (numero, tipo)
);

CREATE TABLE ec_emendas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero            INTEGER NOT NULL UNIQUE,
    data              DATE    NOT NULL,
    ementa            TEXT,
    artigos_alterados INTEGER[]
);

CREATE INDEX idx_capitulos_titulo    ON cf_capitulos(titulo_id);
CREATE INDEX idx_secoes_capitulo     ON cf_secoes(capitulo_id);
CREATE INDEX idx_artigos_titulo      ON cf_artigos(titulo_id);
CREATE INDEX idx_artigos_capitulo    ON cf_artigos(capitulo_id);
CREATE INDEX idx_artigos_tipo        ON cf_artigos(tipo);
CREATE INDEX idx_paragrafos_artigo   ON cf_paragrafos(artigo_id);
CREATE INDEX idx_incisos_artigo      ON cf_incisos(artigo_id);
CREATE INDEX idx_incisos_paragrafo   ON cf_incisos(paragrafo_id);
CREATE INDEX idx_alineas_inciso      ON cf_alineas(inciso_id);
CREATE INDEX idx_vinculos_artigo     ON cf_vinculos(artigo_id);
CREATE INDEX idx_vinculos_decisao    ON cf_vinculos(decisao_id);
CREATE INDEX idx_vinculos_tipo_bloco ON cf_vinculos(tipo_bloco);
CREATE INDEX idx_decisoes_classe     ON stf_decisoes(classe);
CREATE INDEX idx_decisoes_julgamento ON stf_decisoes(data_julgamento);

ALTER TABLE cf_titulos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_capitulos  ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_secoes     ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_subsecoes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_artigos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_paragrafos ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_incisos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_alineas    ENABLE ROW LEVEL SECURITY;
ALTER TABLE stf_decisoes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE cf_vinculos   ENABLE ROW LEVEL SECURITY;
ALTER TABLE stf_sumulas   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ec_emendas    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leitura publica" ON cf_titulos    FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_capitulos  FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_secoes     FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_subsecoes  FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_artigos    FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_paragrafos FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_incisos    FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_alineas    FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON stf_decisoes  FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON cf_vinculos   FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON stf_sumulas   FOR SELECT USING (true);
CREATE POLICY "Leitura publica" ON ec_emendas    FOR SELECT USING (true);
